Further re-org
I still havent decided how I really want the conf loading to work.

For now, settle on git-auto-discover mode only (as its what I use) and
make other cases work later

diff --git a/bin/haxby b/bin/haxby
--- a/bin/haxby
+++ b/bin/haxby
@@ -2,26 +2,21 @@
 
 # Major portions of logic below inspired by https://github.com/jayferd/balls
 
-function haxby::bin::find-lib {
-    HAXBY_LIB=$(dirname $0)/../lib
-    if which greadlink >/dev/null 2>&1
-    then
-        function readlink {
-            greadlink $@
-        }
-    fi
-    HAXBY_LIB=$(readlink -f "$HAXBY_LIB")
-}
+if which greadlink >/dev/null 2>&1
+then
+    function readlink {
+        greadlink $@
+    }
+fi
 
-
-function haxby::bin::search-conf {
+function haxby::bin::search-conf-git {
     HAXBY_CONF=$(find $GIT_ROOT -name 'haxby.conf')
     CONF_COUNT=$(wc -l <<<$HAXBY_CONF)
     if [ "$CONF_COUNT" -gt "1" ]; then
         echo "Found more than one 'haxby.conf', failed auto-conf"
-        unset HAXBY_CONF
+        exit 1
     elif [ "$CONF_COUNT" -eq "0" ]; then
-        echo "No config was auto-discovered or specified, exiting"
+        echo "No config was auto-discovered, exiting"
         exit 1
     fi
     echo $HAXBY_CONF
@@ -29,7 +24,9 @@ function haxby::bin::search-conf {
 
 function haxby::bin::load-conf {
     GIT_ROOT=$(git rev-parse --show-toplevel || true)
-    [[ -n "$GIT_ROOT" ]] && HAXBY_CONF=$(haxby::bin::search-conf)
+    [[ -n "$GIT_ROOT" ]] && HAXBY_CONF=$(haxby::bin::search-conf-git)
+
+    [[ -z "$HAXBY_CONF" ]] && { echo "Config auto-discovery failed, exiting"; exit 1; }
 
     [[ -n "$HAXBY_CONF" ]] && HAXBY_CONF=$(readlink -f $HAXBY_CONF)
     [[ -n "$HAXBY_CONF" ]] && HAXBY_CONF_DIR=$(dirname $HAXBY_CONF)
@@ -42,12 +39,17 @@ function haxby::bin::check-installed-lib {
     . $HAXBY_LIB/haxby.sh || { echo "Failed to find lib directory"; exit 1; }
 }
 
+function haxby::bin::load-lib {
+    HAXBY_LIB=$(dirname $0)/../lib
+    HAXBY_LIB=$(readlink -f "$HAXBY_LIB")
+    . $HAXBY_LIB/haxby.sh 2>/dev/null || haxby::bin::check-installed-lib
+}
+
 mode=$1
 shift
 
-haxby::bin::find-lib
 haxby::bin::load-conf
-. $HAXBY_LIB/haxby.sh 2>/dev/null || haxby::bin::check-installed-lib
+haxby::bin::load-lib
 
 for haxby_mode in $HAXBY_MODES
 do
